### GET TEST REQUEST
GET http://localhost:5000

### GET CATEGORIES
GET http://localhost:5000/categories

### POST USER SIGN-UP 1
POST http://localhost:5000/sign-up
Content-Type: application/json

{
  "username": "user1",
  "password": "testpw"
}

### POST USER SIGN-UP 2
POST http://localhost:5000/sign-up
Content-Type: application/json

{
  "username": "user2",
  "password": "testpw"
}

### POST INVALID SIGN-UP
POST http://localhost:5000/sign-up
Content-Type: application/json

{
  "username": "",
  "passowrd": "testpw"
}

### POST USER LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "user1",
  "password": "testpw"
}

### GET USER GALLERY
GET http://localhost:5000/gallery
x-access-token: 

### GET ALL USER DATA INCLUDING PW
GET http://localhost:5000/all-data
x-access-token: 

### GET MY PROFILE
GET http://localhost:5000/my-profile
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3MTMxODExN30.yue2HIsDkE_LHb8fYRDAte9PZhl-lk5QM2bCXKHiYcQ

### PUT MY PROFILE
PUT http://localhost:5000/edit-my-profile
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3MTMxODExN30.yue2HIsDkE_LHb8fYRDAte9PZhl-lk5QM2bCXKHiYcQ
Content-Type: application/json

{
  "updatedTagline": "this is my tagline",
  "updatedBio": "this is my bio",
  "updatedLinkedin": "https://www.linkedin.com/in/anthonyvngo/" 
}


### GET MY NOWWW ENTRY(S)
GET http://localhost:5000/my-entries
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3MTMxODExN30.yue2HIsDkE_LHb8fYRDAte9PZhl-lk5QM2bCXKHiYcQ

### POST NOWWW ENTRY
POST http://localhost:5000/add-entry
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3MTMxODExN30.yue2HIsDkE_LHb8fYRDAte9PZhl-lk5QM2bCXKHiYcQ
Content-Type: application/json

{
  "content": "learning more SWE stuff",
  "categoryId": 3
}

### PUT NOWWW ENTRY
PUT http://localhost:5000/edit-entry/2
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3MTMxODExN30.yue2HIsDkE_LHb8fYRDAte9PZhl-lk5QM2bCXKHiYcQ
Content-Type: application/json

{
  "updatedContent": "UPDATED !!! learning more SWE stuff",
  "updatedCategoryId": 5
}

### DELETE NOWWW ENTRY
DELETE http://localhost:5000/delete-entry/1
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyMSIsImlhdCI6MTY3MTMxODExN30.yue2HIsDkE_LHb8fYRDAte9PZhl-lk5QM2bCXKHiYcQ